# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f82937beb6bfb12e202ab2e2d26562a9a613dce60d6de451db4580e91523d58b4267753948913329fa0f8fc27d1ae8ec7cdd5798d6a82736feb617fcb2897af

test:
  secret_key_base: 479fcddedfd7a1cc1443327ccda3b3d129a734c5c2e1ba4baf2a0a5e415e98f4b1014b55cbe3c5e0c1a2c0f602f1ce2d5be48ca89bff188350f384ac1b16d562

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
